language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - pip install pytest
  - pip install .
# command to run tests
script: py.test tests/tests.py
